######################################################################
#
# Function to read a time .pos file generated by gmsh
# eg. integration of a view over time
#
# Returns the time series and the values at each time
#
######################################################################

import re
from numpy import array

def readTimepos(fname):
    infile = open(fname, 'r')
    line = infile.readline() # read first line, discard
    line = infile.readline() # read second line (contains time info)

    # Get the time information
    line = re.split('{|}',line)[1]
    t = [float(x) for x in line.split(',')]

    # Read the data
    line = infile.readline()
    line = re.split('\(|\)|{|}',line)
    dat = [float(x) for x in line[3].split(',')]
    return array(t),array(dat)
