######################################################################
#
# Function to read a .pos file generated by the gmsh CutPlane plugin
# (with no volume extraction, eg. when getting the value along a line.)
#
# Returns the x,y,z coordinates of the cut plane and the value along
# that plane
#
######################################################################

from numpy import *
import re

def read_cutplane_pos(fname):

    x = [];
    y = [];
    z = [];
    value = [];

    with open(fname) as f:
        for line in f:
            if 'SL(' in line:
                line =  re.split(r'[,|(|)|{|}]',line) 
                x.extend([float(line[1]),float(line[4])])
                y.extend([float(line[2]),float(line[5])])
                z.extend([float(line[3]),float(line[6])])
                value.extend([float(line[8]),float(line[9])])
    return x,y,z,value
    
