######################################################################
#
# Function to read a .pos file generated by the gmsh isosurface plugin
# (with no volume extraction, eg. when getting the isosurface of an
# interface).
#
# Returns the x,y coordinates of that interface
#
######################################################################

from numpy import *
import re

def read_isosurface_pos(fname):

    x = [];
    y = [];

    with open(fname) as f:
        for line in f:
            if 'SL(' in line:
                line =  re.split(r'[,|(|)]',line) 
                x.extend([float(line[1]),float(line[4])])
                y.extend([float(line[2]),float(line[5])])
                #z.extend([float(line[3]),float(line[6])])
    return x,y
    
